#based on https://github.com/giannisigalotti/HomeAssistant/blob/main/blueprints/motion-activated-light.yaml
blueprint:
  name: Motion-activated Light outdoor brightness
  description: Turn on a light when a movement occurs
  domain: automation
  source_url: https://github.com/hebbister/blueprints/blob/main/motion-activated-outdoor-brightness.yaml
  input:
    brightness_entity:
      name: External brightness (0–100%)
      description: |
        External brightness sensor or number entity (0–100).
        Automation runs only if brightness is below threshold.
        If you do not select an entity, it won't be taken into account.
      selector:
        entity:
          domain:
            - sensor
            - number
      default: ""
    brightness_threshold:
      name: Brightness threshold (%)
      description: |
        Above this value the automation will NOT run.
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
      default: 60

    motion_entity:
      name: Motion sensor
      selector:
        entity:
          domain:
            - binary_sensor
          device_class:
            - occupancy
          reorder: false
          multiple: false
    light_target:
      name: Light
      selector:
        target:
          entity:
            - domain:
                - light
    no_motion_wait:
      name: Wait time
      description:
        The time to wait before turning off the light after no movement
        is detected.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    skip_if_light_is_on:
      name:
        Do not execute if the light is already on (prevent auto-turn-off if the
        light was turned on manually).
      selector:
        boolean: {}
      default: false
    no_sunset_handling:
      name: Disable day/night management?
      description:
        When you turn this option to off, you can define how many hour
        before sunset and after sunshine the automation turn on the light
      selector:
        boolean: {}
      default: false
    wheater_handling:
      name: Enable meteo managment?
      description:
        Does it also take weather into account to enable/disable motion
        sensors (use the time range only when it's sunny and disable otherwise)?
      selector:
        boolean: {}
      default: false
    wheater_entity:
      name: Weather status sensor
      description:
        This sensor is used only with the Meteo managment option to determine
        if the weather is sunny or not (useful if you are in a room usually dark in
        case of bad weather condition
      selector:
        entity:
          domain:
            - weather
          multiple: false
          reorder: false
      default: weather.forecast_home
    sunset_start_hh:
      name: Pre-sunset hours activation
      description:
        How many hours before sunset does the management activate (negative
        numbers indicate a delay)?
      selector:
        number:
          min: 0.0
          max: 12.0
          unit_of_measurement: hours
          step: 1.0
          mode: slider
      default: 0
    sunset_start_mm:
      name: Pre-sunset minutes activation
      description:
        How many minutes before sunset does the management activate (negative
        numbers indicate a delay)?
      selector:
        number:
          min: 0.0
          max: 59.0
          unit_of_measurement: minutes
          step: 1.0
          mode: slider
      default: 0
    sunrise_start_hh:
      name: Post-sunrise hours activation
      description:
        How many hours after sunrise does the management deactivate (negative
        numbers indicate an advance)?
      selector:
        number:
          min: 0.0
          max: 12.0
          unit_of_measurement: hours
          step: 1.0
          mode: slider
      default: 0
    sunrise_start_mm:
      name: Post-sunrise minutes activation
      description:
        How many minutes after sunrise does the management deactivate (negative
        numbers indicate an advance)?
      selector:
        number:
          min: 0.0
          max: 59.0
          unit_of_measurement: minutes
          step: 1.0
          mode: slider
      default: 0
    timeout:
      name: "Deactivation timeout?"
      description: "After how many minutes does the switch turn off automatically (-1 if no timeout)"
      selector:
        number:
          min: -1
          max: 60
          unit_of_measurement: minutes
      default: -1
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input motion_entity
  to: "on"
variables:
  dusk_start_hour: !input sunset_start_hh
  dusk_start_minute: !input sunset_start_mm
  rising_start_hour: !input sunrise_start_hh
  rising_start_minute: !input sunrise_start_mm
  use_weather: !input wheater_handling
  skip_light_on: !input skip_if_light_is_on
  target_lights: !input light_target

  sun_rising:
    "{% if (states.sun.sun.state == \"above_horizon\") %}\n    {{ states.sun.sun.last_changed
    }}\n{%- else -%}\n    {{ states.sun.sun.attributes.next_rising }}\n{%- endif %}\n"
  sun_dusk:
    "{% if (states.sun.sun.state == \"above_horizon\") %}\n    {{ states.sun.sun.attributes.next_dusk
    }}\n{%- else -%}\n    {{ states.sun.sun.last_changed }}\n{%- endif %}\n"
  wheater_sensor: !input wheater_entity
  no_sunny_wheater: "{{ states(wheater_sensor) != 'sunny' and use_weather }}

    "
  brightness_sensor: !input brightness_entity
  brightness_limit: !input brightness_threshold
  brightness_block: >
    {% if brightness_sensor == "" %}
      false
    {% else %}
      {{ states(brightness_sensor) | float(0) > brightness_limit }}
    {% endif %}
    second_target_lights: !input second_light_target

  night_light_target: >
    {{
      second_target_lights
      if second_target_lights.entity_id is defined
         or second_target_lights.device_id is defined
      else target_lights
    }}

  is_night: >
    {{
      as_timestamp(now()) >=
        (as_timestamp(sun_dusk) - dusk_start_hour*3600 - dusk_start_minute*60)
      and
      as_timestamp(now()) <
        (as_timestamp(sun_rising) + rising_start_hour*3600 + rising_start_minute*60)
    }}

  effective_light_target: >
    {{
      night_light_target if is_night else target_lights
    }}

  all_light_entities: >
    {{
      expand(
        (
          ([] if target_lights.device_id is undefined
           else target_lights.device_id | device_entities
           if target_lights.device_id is string
           else target_lights.device_id | map('device_entities') | sum(start=[]))
          +
          ([] if target_lights.entity_id is undefined
           else [target_lights.entity_id]
           if target_lights.entity_id is string
           else target_lights.entity_id)
          +
          ([] if second_target_lights.device_id is undefined
           else second_target_lights.device_id | device_entities
           if second_target_lights.device_id is string
           else second_target_lights.device_id | map('device_entities') | sum(start=[]))
          +
          ([] if second_target_lights.entity_id is undefined
           else [second_target_lights.entity_id]
           if second_target_lights.entity_id is string
           else second_target_lights.entity_id)
        )
        | select('search', '^light\.')
        | unique
        | list
      )
    }}

  force_skip: >
    {{
      skip_light_on and
      (
        all_light_entities
        | selectattr('state', 'eq', 'on')
        | list
        | length > 0
      )
    }}

condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ not brightness_block }}"
      - condition: template
        value_template: "{{ not force_skip }}"
      - condition: or
        conditions:
          - condition: template
            value_template: !input no_sunset_handling
          - condition: template
            value_template: "{{ no_sunny_wheater }}"
          - condition: and
            conditions:
              - "{{ as_timestamp(now()) >= ((as_timestamp(sun_dusk) - dusk_start_hour*3600
                - dusk_start_minute*60) )}}"
              - "{{ as_timestamp(now()) < ((as_timestamp(sun_rising) + rising_start_hour*3600
                + rising_start_minute*60) )}}"
action:
  - service: light.turn_on
    target: "{{ effective_light_target }}"
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
    timeout:
      hours: 0
      minutes: !input timeout
      seconds: 0
      milliseconds: 0
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: "{{ all_light_entities | map(attribute='entity_id') | list }}"
